modules:
- arguments:
  - infile:
  - outfile:
  - digit:
  name: ModuleOne
- arguments:
  - infile:
  - outfile:
  - digit:
  exclusive:
  - forward
  - reverse
  name: ModuleTwo
  optionals:
  - forward:
  - reverse:
- arguments:
  - infile:
  - outfile:
  - digit:
  name: ModuleThree
