default: all

all:
	g++ module1.cpp parsing.cpp -std=c++11 -o ../module1
	g++ module2.cpp parsing.cpp -std=c++11 -o ../module2
	g++ module3.cpp parsing.cpp -std=c++11 -o ../module3

clean:
	-rm -f ../module1
	-rm -f ../module2
	-rm -f ../module3
